### ISSUE TITLE
Do you support writing `lnurlw://mydomain.com` links to bolt cards?

### ISSUE THREAD

**Issue by raweber42** [slaapyhoofd/brrr#90]
See question above. So far I only see `lightning:LNURLxxxx` links being created and written to the cards 😅

**Comment by arbadacarbaYK** [comment]
Its by design. Its no boltcard batchwriting tool but a voucher batchwriting tool. For the use case of batchwriting vouchers for conferences, where the voucher amount usually is redeemed by the confs or the server taken down when the event is over, the resetup by the users of boltcards is pretty complex. 

If you need it though Lee made a boltcard batchwriting cli tool and also BTCpay has a boltcard batchwriting tool in its POS.

**Comment by raweber42** [comment]
Alright, thanks :) makes sense 👍
